from app.models import db, ProductImage, environment, SCHEMA
from sqlalchemy.sql import text # type: ignore


def seed_product_images():
    seeds = [
        ProductImage(
            product_id=1,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/001-01-quantum-warp-drive_netawo.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=1,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/001-02-quantum-warp-drive_pzn4ix.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=1,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/001-03-quantum-warp-drive_cgx1hq.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=2,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/002-01-neutrino-vessel-shielding_jnvhht.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=3,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/003-01-hoverbike-x2000_xihebf.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=3,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/003-02-hoverbike-x2000_fvrray.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=4,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/004-01-uniwheel_wjqwij.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=4,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/004-02-uniwheel_chnceu.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=5,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/005-01-stellarmap-gps_jdrzki.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=5,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999603/Astro/005-02-stellarmap-gps_trw8es.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=6,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999603/Astro/006-01-personal-plasma-shield_pcpqui.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=7,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999603/Astro/007-01-quantum-weave-spacesuit_vjdono.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=8,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/008-01-graviton-boots_ux4sqb.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=8,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999601/Astro/008-02-graviton-boots_w0yh6k.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=9,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/009-01-space-tent_vmpilu.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=10,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999602/Astro/010-01-quantum-entanglement-communicator_q9p1kk.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=11,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999603/Astro/011-01-universal-translator_s6mlqt.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=11,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999603/Astro/011-02-universal-translator_bjniug.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=12,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/012-01-ar-goggles_fqtz4t.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=12,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/012-02-ar-goggles_pwrgd6.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=13,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/013-01-hololens-projector_uhrrkz.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=14,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/014-01-nuclear-battery-pack_qzy3d1.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=15,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999604/Astro/015-01-crystal-harmonizer_n9fb52.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=16,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999605/Astro/016-01-robochef_apaiyr.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=16,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999605/Astro/016-02-robochef_rntlvi.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=17,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999605/Astro/017-01-robob_e2entw.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=17,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999605/Astro/017-02-robob_deboiz.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=18,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/018-01-holographic-memory-projector_mprfj9.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=19,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/019-01-vr-gaming-suit_nbkjcu.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=19,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/019-02-vr-gaming-suit_du20is.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=20,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/020-01-4d-immersive-sound_d6tjvu.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=21,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/021-01-orbital-lounge-chair_fxbikt.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=22,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999606/Astro/022-01-asteroid-bean-bag_mjo9ts.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=23,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/023-01-galaxyglass-table_iklpzv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=24,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/024-01-cosmic-ray-light_vxxzqx.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=25,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/025-01-cosmic-vortex-statue_gs627r.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=25,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/025-02-cosmic-vortex-statue_ss5a9n.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=26,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/026-01-smartfridge-gx_xlca3i.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=26,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999607/Astro/026-02-smartfridge-gx_gpu0li.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=27,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999608/Astro/027-01-solar-oven_r4gkgm.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=28,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999609/Astro/028-01-atomclean-washing-machine_kxl6ya.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=29,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999608/Astro/029-01-chefmate-galactic-utensils_ry1y7n.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=29,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999614/Astro/029-02-chefmate-galactic-utensils_olyfmz.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=30,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999614/Astro/030-01-molecular-gastronomy-kit_bjspse.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=31,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999614/Astro/031-01-zero-g-coffee-maker_fhepar.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=31,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999614/Astro/031-02-zero-g-coffee-maker_wt7qod.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=31,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999614/Astro/031-03-zero-g-coffee-maker_s59d6m.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=32,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/032-01-orbiting-garden-decor_qoxtdx.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=32,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/032-02-orbiting-garden-decor_whthw4.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=33,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/033-01-ecogrow-smart-greenhouse_gofy4c.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=34,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/034-01-gravity-jeans_wqgiid.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=34,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/034-02-gravity-jeans_hgqc1i.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=34,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999615/Astro/034-03-gravity-jeans_jqnqgh.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=35,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999616/Astro/035-01-thermaltech-jacket_jwdg3x.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=35,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999616/Astro/035-02-thermaltech-jacket_nbfe6s.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=35,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999616/Astro/035-03-thermaltech-jacket_jthigl.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=35,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999616/Astro/035-04-thermaltech-jacket_rif1ae.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=36,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999616/Astro/036-01-cosmo-tunic_ymtj08.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=37,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999620/Astro/037-01-astrobelt_kyehef.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=37,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999620/Astro/037-02-astrobelt_rrzb64.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=38,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999620/Astro/038-01-astroglasses_u7mzcv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=38,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/038-02-astroglasses_i9w6i4.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=38,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/038-03-astroglasses_c6dt5p.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=39,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/039-01-eclipse_tlskqv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=39,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999622/Astro/039-02-eclipse_uxayde.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=40,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/040-01-frazorks_ijviqj.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=40,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/040-02-frazorks_mwyw5o.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=41,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999621/Astro/041-01-mars-colony_equ6ms.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=42,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999622/Astro/042-01-microbe-super-nova_xzae3g.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=43,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999622/Astro/043-01-the-void-starset-horizon_fmsqap.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=44,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999622/Astro/044-01-alien-jazz-experience_ls37kj.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=45,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999622/Astro/045-01-zeb-bars-beyond-mars_a0q9dc.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=46,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/046-01-intergalactic-botany-illustrated_b8tybo.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=47,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/047-01-the-quantum-chef_hbcexd.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=48,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/048-01-starship-engineering-for-dummies_mevyca.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=49,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/049-01-vector-tennis-racket_dbkwif.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=49,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/049-02-vector-tennis-racket_em5pie.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=50,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999626/Astro/050-01-p79-galactic-golf-clubs_hlgh25.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=51,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/051-01-interstellar-fishing-rod_nmmkbe.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=51,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/051-02-interstellar-fishing-rod_jimp3a.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=51,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/051-03-interstellar-fishing-rod_lmg7vy.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=52,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/052-01-astrochess-set_vuzlyb.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=52,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/052-02-astrochess-set_tnesg2.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=53,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999627/Astro/053-01-quantum-card-deck_kzebik.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=53,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999628/Astro/053-02-quantum-card-deck_f99xzu.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=54,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999628/Astro/054-01-cosmic-puzzle-collection_ge6f9p.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=54,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999628/Astro/054-02-cosmic-puzzle-collection_wjvz5c.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=54,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999628/Astro/054-03-cosmic-puzzle-collection_pyeglx.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=55,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999631/Astro/055-01-astrocanvas-art-kit_l11e8x.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=55,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999632/Astro/055-02-astrocanvas-art-kit_wsojvl.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=56,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999632/Astro/056-01-astrophotography-kit_btpbfh.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=57,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/057-01-interstellar-canvas-print_e5h6hb.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=58,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/058-01-cosmic-relic-detector_fsx2io.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=59,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/059-01-starship-enterprise-miniature_nmqgoo.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=60,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/060-01-star-crystal_of25yf.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=61,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/061-01-first-mars-landing_hungxr.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=61,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999633/Astro/061-02-first-mars-landing_mh8ujg.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=62,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999634/Astro/062-01-astromeal-pack_tmt8mu.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=63,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999634/Astro/063-01-meteorite-meal-kit_byohak.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=64,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999637/Astro/064-01-galactic-granola-bars_jbniyv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=65,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999634/Astro/065-01-zero-g-freeze-dried_edbejj.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=66,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999637/Astro/066-01-astrobrew-coffee-beans_mavvye.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=67,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999637/Astro/067-01-quantum-quench_xd7oql.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=68,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999637/Astro/068-01-astroade_rd8bsl.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=69,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/069-01-nanobristle-toothbrush_v7i9dy.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=70,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999637/Astro/070-01-lunarhydrate-facial-lotion_cnud3q.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=70,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/070-02-lunarhydrate-facial-lotion_ixx8kj.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=70,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/070-03-lunarhydrate-facial-lotion_q3pltx.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=71,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/071-01-stellarshade-foundation_lxxwcv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=72,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/072-01-galaxyglow-lip-tint_tmu4nj.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=72,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/072-02-galaxyglow-lip-tint_kdlhzl.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=73,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999638/Astro/073-01-stardust-perfume_gveeqc.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=74,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999642/Astro/074-01-photon-health-scanner_cnar1s.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=75,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999642/Astro/075-01-simulation-treadmill_h7defv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=76,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999642/Astro/076-01-vg-yoga-mat_anydwq.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=77,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999642/Astro/077-01-galactic-antiviral-kit_et0jnf.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=78,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999643/Astro/078-01-stellar-elixir_eopyyq.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=79,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999642/Astro/079-01-nanite-healing-spray_vby2sw.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=80,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999643/Astro/080-01-nanobot-tissue-repair_kvgbou.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=81,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999643/Astro/081-01-fluff_bg25pv.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=81,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999643/Astro/081-02-fluff_rj3jct.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=81,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999643/Astro/081-03-fluff_lbjj3s.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=81,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/081-04-fluff_nz5l3h.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=82,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/082-01-nebulafish_ldp4yq.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=82,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/082-02-nebulafish_ogqhgd.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=82,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/082-03-nebulafish_pydbhu.jpg',
            thumbnail=False
        ),
        ProductImage(
            product_id=83,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/083-01-astropet-holo-collar_ozqdme.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=84,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999644/Astro/084-01-cosmic-pet-grooming-kit_bwkhj7.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=85,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999645/Astro/085-01-astrofish-aquarium_zxsqcy.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=86,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999645/Astro/086-01-exo-flora-terrarium_ugp3ls.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=87,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999645/Astro/087-01-cosmic-chew-ring_uegg7e.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=88,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999647/Astro/088-01-orbit-ball_rarnwh.jpg',
            thumbnail=True
        ),
        ProductImage(
            product_id=89,
            url='https://res.cloudinary.com/dt2uyzpbn/image/upload/v1714999652/Astro/089-01-quantum-laser-pointer_gez9kl.jpg',
            thumbnail=True
        )
    ]

    for product_image in seeds:
        db.session.add(product_image)
    db.session.commit()


def undo_product_images():
    if environment == 'production':
        db.session.execute(f'TRUNCATE table {SCHEMA}.product_images RESTART IDENTITY CASCADE;')
    else:
        db.session.execute(text('DELETE FROM product_images'))
    db.session.commit()
